### ISSUE TITLE
ngx-jodit: icons always showing text, not SVG / PNG

### ISSUE THREAD

**Issue by ivan-price-acted** [julianpoemp/ngx-jodit#18]
### Package versions

| package          | version |
|---------------|---------|
| Angular           |    16.2.6           |
| jodit                |     4.0.0-beta.87          |
|ngx-jodit         | ^3.0.0-beta.8" (same behavior for v2)  |

The toolbar for Jodit is always showing text buttons, never icons for the buttons. Group buttons display icons correctly, but buttons such as (e.g.) bold show the word 'bold', not the icon.

The actual bold functionality works fine.

<img width="362" alt="image" src="https://github.com/julianpoemp/ngx-jodit/assets/93131836/136713e7-7753-4d20-9f92-e41c0bdaa6db">

This occurs when i supply any list of buttons to the jodi `[options]` input, e.g.:

```
public joditOptions: any = {
    buttons: ['bold', 'underline'],
    textIcons: false
}

----

<ngx-jodit [(value)]="text" [options]="joditOptions"></ngx-jodit>
```
Setting textIcons to true transforms the 'menu' icons to text.

Any ideas what i'm doing wrong ?

thanks

**Comment by julianpoemp** [comment]
@ivan-price-acted thanks for reporting this issue! Maybe related to #8 . I'll have a look at it asap.

**Comment by julianpoemp** [comment]
@ivan-price-acted I just released new versions of ngx-jodit 2.x and 3.x. Please update to the latest version.

The issue occurred because typing/esm issues with the jodit package. I don't know why but the Jodit developers don't get the typings working like other packages. That's why we have to use the compiled JS files from Jodit. That's a breaking change, please have a look on the new installation instructions. It's related to #9.

**Comment by ivan-price-acted** [comment]
@julianpoemp thanks for your rapid response !

i can confirm that after bumping to version `3.0.0-beta.9`, and adding `"node_modules/jodit/es5/jodit.fat.min.js"` to the angular.json `scripts` list the icons are back.. however i'm concerned that including jodit.fat.min.js (>700K !) will increase the weight of our app with functionality we won't use.

it seems a high price to pay for icons in the toolbar, we would probably prefer text icons and save the bandwidth for our network-sensitive application. Is there any other workaround, are Jodit aware of this limitation ? We are planning on paying for the pro version of Jodit, should we take it up with them ?

thanks very much for your work on this project !

-i

**Comment by julianpoemp** [comment]
@ivan-price-acted did you try one of the other jodit js files? Perhaps there is a smaller one.

At the moment I don't recommend to use Jodit if you are looking for well written Typescript libraries. I didn't get the import of Jodit working for ngx-jodit because there are any issues every time (like your issue with the icons).

Btw Jodit v4 and jodit-pro v2 are in beta, I don't recommend to use it on production.

I really don't know what Jodit is doing wrong. Perhaps something with their build system.

The problem of the large size is because we are not using ESM modules so Angular imports commonjs builds without the option to select only code it needs. Jodit should get ESM working.

**Comment by ivan-price-acted** [comment]
Hi there,

i tried out a custom build, and got it down to 300K.. but that still seems a lot considering we only want very simple functionality.. and we'd be obliged to re-build manually and no longer manage the version via our package.json which i don't love.

i thank you very much for this library and your work on this subject, it may be that we end up using the custom build if we can't find anything smaller / mode modular.

**Comment by julianpoemp** [comment]
@ivan-price-acted I reported this issue to Jodit ([#1029](https://github.com/xdan/jodit/issues/1029)). Perhaps a solution will be found soon.

**Comment by julianpoemp** [comment]
update: Jodit is working on a solution. It's confirmed that this issue is a bug. I'm confident that we can use the ESM version again. As soon as I can confirm it's working I'll release a new version of ngx-jodit 2.x and 3.x .

Reopening this issue.

**Comment by ivan-price-acted** [comment]
ok thanks @julianpoemp we'll take a look at that !
