### ISSUE TITLE
ngx-jodit-pro: ngx-jodit-pro can't be used with template driven or reactive forms

### ISSUE THREAD

**Issue by wwstrothe** [julianpoemp/ngx-jodit#35]
Describe the issue as detailed as possible, in a way I can reproduce it easily.
Upgraded to Jodit Pro, and now Jodit isn't working in the reactive and template driven forms I already had built. 
I updated the standalone file import to import NgxJoditProComponent and updated the component in the template to <ngx-jodit-pro>

### Previous Package versions
| package          | version |
|---------------|---------|
| Angular           |  v16.2.0. |
| ngx-jodit         |  ^3.1.2    |
| jodit                 |  ^4.0.18  |

### Pro Package versions

| package          | version |
|---------------|---------|
| Angular           |  v16.2.0. |
| ngx-jodit-pro  |  ^3.0.0-beta.6  |
| jodit                 |  ^4.0.0-beta.121  |
| jodit-pro          |  ^2.0.0-beta.76  |

**Comment by julianpoemp** [comment]
@wwstrothe  Currently ngx-jodit pro isn't supporting template driven or reactive forms. I'll dive into it.

Another topic: Because of issue #34 . Do you see any documentation about Jodit Pro v4 using ESM successfully? Or a documentation about using it with Typescript successfully? I didn't buy Jodit Pro so I can't see it myself. I'd highly appreciate any helpful information.

**Comment by julianpoemp** [comment]
@wwstrothe I just released ngx-jodit-pro v3 with jodit-pro v4 support and template driven or reactive form support. Please check the installation [instructions](https://github.com/julianpoemp/ngx-jodit/blob/main/libs/ngx-jodit-pro/README.md) for changes.
